dbset<-read.table("./household_power_consumption.txt", header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
subsetdb<-dbset[dbset$Date %in% c("1/2/2007","2/2/2007") ,]
datetime<-strptime(paste(subsetdb$Date, subsetdb$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
gapow<-as.numeric(subsetdb$Global_active_power)
grpow<-as.numeric(subsetdb$Global_reactive_power)
volt<-as.numeric(subsetdb$Voltage)
subMet1<-as.numeric(subsetdb$Sub_metering_1)
subMet2<-as.numeric(subsetdb$Sub_metering_2)
subMet3<-as.numeric(subsetdb$Sub_metering_3)
png("plot4.png", width=480, height=480)
par(mfrow = c(2, 2)) 
plot(datetime,gapow,type="l", xlab="", ylab="Global Active Power", cex=0.2)
plot(datetime,volt,type="l", xlab="datetime", ylab="Voltage")
plot(datetime, subMet1, type="l", ylab="Energy Submetering", xlab="")
lines(datetime, subMet2, type="l", col="red")
lines(datetime, subMet3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=, lwd=2.5, col=c("black", "red", "blue"), bty="o")
plot(datetime,grpow, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()